Fingoo-org/Fingoo

README.md

EI-34 git-jira test

---

README.md

EI-35 restore README.md

---

api/src/app.module.ts
api/src/config/typeorm.config.service.ts

- typeORM 설정입니다.
- 환경변수를 입력해서 사용합니다.

[api] chore: typeORM

---

api/src/numerical-guidance/test/unit-test/query/get-fluctuatingIndicator-without-cache.query.handler.spec.ts
api/src/numerical-guidance/test/unit-test/query/get-flucuatingIndicators.query.handler.spec.ts

 EI-104: redis-krx 통합 확인

---

api/src/numerical-guidance/test/integration-test/api/numerical-guidance.controller.spec.ts

✅ 작업 내용
- test에서 url 이 잘못들어가 변경했습니다.

[EI-125] [api] test: test url 변경

---

web/__tests__/components/numerical-guidance/indicators-chart.test.tsx
web/app/ui/components/numerical-guidance/indicators-chart.tsx
web/app/ui/components/view/atom/editable-text.tsx
web/app/ui/components/view/molocule/alert-dialog/alert-dialog-negative-button.tsx
web/app/ui/components/view/molocule/alert-dialog/alert-dialog-positive-button.tsx
web/app/ui/components/view/molocule/multi-line-chart.tsx

✅ 작업 내용
- editable-text component를 개발했습니다.
- 재사용 가능한 수준으로 컴포넌트를 리팩토링 했습니다.
- 텍스트를 수정가능하도록 할 때 UX 적으로 고민이 있었습니다. 디자이너인 수연씨와 의논하여 hover 시 수정할 수 있는 단서(밑줄 애니메이션)을 제공하여 사용자가 수정가능함을 깨닫도록 하였습니다
- 수정가능한 텍스트를 만들 때 div 태그의 contentable 속성과 input 태그 중 사용을 고민했습니다. 처음에는 contentable 속성을 사용해 구현했으나 1. react와 호환이 좋지 않음, 2. 지원하는 이벤트의 미흡 등을 이유로 input 태그로 전환했습니다

Ei 128 refactor

---

web/__tests__/components/numerical-guidance/indicator-list.test.tsx
web/__tests__/components/numerical-guidance/metadata-list.test.tsx
web/__tests__/components/numerical-guidance/selected-metadata-title.test.tsx
web/__tests__/hooks/use-indicator-metadata-list.hook.test.tsx
web/__tests__/hooks/use-selected-indicator-board-metadata.hook.test.tsx
web/__tests__/stores/numerical-guidance.store.test.ts
web/app/business/hooks/use-selected-indicator-board-metadata.hook.ts
web/app/mocks/db.mock.ts
web/app/mocks/handlers.mock.ts
web/app/store/querys/api-path.ts
web/app/store/querys/fetcher.ts
web/app/store/querys/numerical-guidance/indicator-board-metadata.query.ts
web/app/store/stores/numerical-guidance.store.ts
web/app/ui/components/numerical-guidance/indicators-chart.tsx
web/app/ui/components/numerical-guidance/selected-metadata-title.tsx
web/app/ui/components/view/atom/editable-text.tsx
web/package-lock.json
web/package.json

✅ 작업 내용
- 사용자가 메타데이터 이름을 편집할 수 있는 selected-metadata-title 컴포넌트를 개발했습니다.
- 사용자가 메타데이터를 수정할 수 있는 비즈니스 로직을 작성했습니다.
- 컴포넌트와 비즈니스 로직에 대한 테스트를 작성했습니다.
- usedebounce 훅을 사용하여 api 요청 수를 최적화했습니다.

Ei 133 debounce

---

web/app/utils/helper.ts

[EI-129] [web] fix: rollback filterChildrenByType fn

---

api/src/utils/seeds/indicator-list.entity.seeder.ts

✅ 작업 내용
- seeders에 Market type에 맞춰 코드 수정

[EI-136] [api] refactor: seeders에 Market type에 맞춰 코드 수정

---

api/src/numerical-guidance/application/query/get-fluctuatingIndicator/fluctuatingIndicator.dto.ts

[EI-132] [api] refactor: resolve conflict

---

api/package-lock.json
api/src/numerical-guidance/api/numerical-guidance.controller.ts
api/src/numerical-guidance/application/command/delete-indicator-board-metadata/delete-indicator-board-metadata.command.handler.ts
api/src/numerical-guidance/application/command/delete-indicator-board-metadata/delete-indicator-board-metadata.command.ts
api/src/numerical-guidance/application/port/persistence/delete-indicator-board-metadata.port.ts
api/src/numerical-guidance/infrastructure/adapter/persistence/indicator-board-metadata.persistent.adapter.ts
api/src/numerical-guidance/numerical-guidance.module.ts
api/src/numerical-guidance/test/E2E test/nemerical-guidance.e2e.spec.ts
api/src/numerical-guidance/test/integration-test/adapter/persistence/indicator-board-metadata.persistent.adapter.spec.ts
api/src/numerical-guidance/test/unit-test/command/delete-indicator-board-metadata.command.handler.spec.ts

✅ 작업 내용
- 지표보드 메타데이터 삭제 작업을 했습니다.
- 예외 처리에 통일성을 주었습니다. -> 해당 응답값은 밥 먹고와서 작업할게요
- 의존성에서 문제가 생겨서 해결했습니다.

[EI-139] 지표보드 메타데이터 삭제

---

api/src/auth/auth.controller.ts

[EI-148] [api] fix: import 수정

---

api/package.json
api/src/utils/database/seeds/data-source.ts
api/src/utils/database/seeds/indicator-list.entity.seeder.ts

[EI-138] [api] chore: fix seeding

---

api/src/main.ts
api/src/numerical-guidance/api/dto/get-fluctuatingIndicator.dto.ts
api/src/numerical-guidance/api/numerical-guidance.controller.ts
api/src/numerical-guidance/application/query/get-fluctuatingIndicator/fluctuatingIndicator.dto.ts
api/src/numerical-guidance/application/query/get-history-indicator/history-indicator.dto.ts
api/src/numerical-guidance/application/query/get-indicator/indicator.dto.ts
api/src/numerical-guidance/application/query/get-indicator/indicators.dto.ts
api/src/numerical-guidance/domain/indicator-board-metadata.ts
api/src/numerical-guidance/infrastructure/adapter/persistence/indicator-board-metadata/indicator-board-metadata.persistent.adapter.ts
api/src/numerical-guidance/test/E2E test/numerical-guidance.e2e.spec.ts
api/src/utils/exception-filter/api-exception-response.decorator.ts
api/src/utils/exception-filter/http-exception-filter.ts
api/src/utils/pagination/api-paginated-response.decorator.ts
api/src/utils/pagination/cursor-page.dto.ts

✅ 작업 내용
- swagger를 통한 api 문서화 작업을 진행했습니다. 
- response에 대한 형식을 통일하고, 해당 api resposne를 custom decorator를 통해 작업했습니다.

[EI-165] swagger refactoring

---

api/src/numerical-guidance/api/dto/get-history-indicator.dto.ts
api/src/numerical-guidance/api/numerical-guidance.controller.ts
api/src/numerical-guidance/application/port/persistence/indicator/load-history-indicator-value.port.ts
api/src/numerical-guidance/application/port/persistence/indicator/load-history-indicator.port.ts
api/src/numerical-guidance/application/query/get-history-indicator/get-history-indicator.query.handler.ts
api/src/numerical-guidance/application/query/get-history-indicator/get-history-indicator.query.ts
api/src/numerical-guidance/infrastructure/adapter/persistence/history-indicator/history-indicator.persistent.adapter.ts
api/src/numerical-guidance/test/E2E test/numerical-guidance.e2e.spec.ts
api/src/numerical-guidance/test/integration-test/adapter/persistence/history-indicator.persistent.adapter.spec.ts
api/src/numerical-guidance/test/unit-test/query/get-history-indicator.query.handler.spec.ts

✅ 작업 내용
- history cursor pagination 개수 기반으로 변경
- history cursor pagination을 startDate - endDate 기반에서 dataCount(개수) 기반으로 변경했습니다.

[EI-168] history cursor pagination 개수 기반으로 변경

---

api/docker-compose-api.yml
api/src/numerical-guidance/api/numerical-guidance.controller.ts
api/src/numerical-guidance/infrastructure/adapter/persistence/custom-forecast-indicator/custom-forecast-indicator.persistent.adapter.ts
data-modeling-api/service.py

[EI-49] [api] refactor: ApiException, base url 환경변수 수정

---

api/src/numerical-guidance/api/numerical-guidance.controller.ts
api/src/numerical-guidance/test/E2E test/numerical-guidance.e2e.spec.ts
web/__tests__/components/numerical-guidance/custom-forecast-indicator/custom-forecast-indicator-list.test.tsx
web/__tests__/hooks/indicator-board-metadata/use-indicator-board-metadata-list-view-model.hook.test.tsx
web/__tests__/hooks/indicator-board-metadata/use-selected-indicator-board-metadata-view-model.hook.test.tsx
web/app/business/hooks/custom-forecast-indicator/use-custom-forecast-indicator-list-view-model.hook.ts
web/app/business/hooks/custom-forecast-indicator/use-selected-custom-forecast-indicator-view-model.tsx
web/app/business/hooks/indicator-board-metedata/use-selected-indicator-board-metadata-view-model.hook.ts
web/app/business/services/view-model/custom-forecast-indicator-view-model.service.ts
web/app/business/services/view-model/indicator-board-metadata-view-model.service.ts
web/app/mocks/db/custom-forecast-indicator-action.mock.ts
web/app/mocks/db/index.ts
web/app/mocks/db/indicator-board-metadata-action.mock.ts
web/app/mocks/handlers/indicator-board-metadata-handler.mock.ts
web/app/store/querys/numerical-guidance/custom-forecast-indicator.query.ts
web/app/store/querys/numerical-guidance/indicator-board-metadata.query.ts
web/app/ui/components/numerical-guidance/custom-forecast-indicator/custom-forecast-indicator-list-item.tsx
web/app/ui/components/numerical-guidance/indicator-board-metadata/metadata-list.tsx

Ei 175 create

---

web/__tests__/components/numerical-guidance/custom-forecast-indicator/custom-forecast-indicator-dialog-menu.test.tsx
web/__tests__/components/numerical-guidance/custom-forecast-indicator/custom-forecast-indicator-list.test.tsx
web/app/business/hooks/custom-forecast-indicator/use-custom-forecast-indicator-list-view-model.hook.ts
web/app/business/hooks/custom-forecast-indicator/use-selected-custom-forecast-indicator-view-model.tsx
web/app/business/hooks/indicator-board-metedata/use-selected-indicator-board-metadata-view-model.hook.ts
web/app/business/services/view-model/custom-forecast-indicator-view-model.service.ts
web/app/business/services/view-model/indicator-board-metadata-view-model.service.ts
web/app/mocks/db/custom-forecast-indicator-action.mock.ts
web/app/mocks/db/indicator-board-metadata-action.mock.ts
web/app/mocks/handlers/custom-forecast-indicator-handler.mock.ts
web/app/mocks/handlers/indicator-board-metadata-handler.mock.ts
web/app/store/querys/api-path.ts
web/app/store/querys/numerical-guidance/custom-forecast-indicator.query.ts
web/app/store/querys/numerical-guidance/indicator-board-metadata.query.ts
web/app/ui/components/numerical-guidance/custom-forecast-indicator/custom-forecast-indicator-dialog-menu/custom-forecast-indicator-dialog-menu.tsx
web/app/ui/components/numerical-guidance/custom-forecast-indicator/custom-forecast-indicator-list/custom-forecast-indicator-list-item.tsx
web/jest.config.ts

Ei 184 forecast

---

api/.dockerignore
api/src/app.module.ts
api/src/utils/config/redis.config.service.ts
docker-compose-dev.yml
docker-compose-test.yml
docker-compose.yml

Ei 185 presetting

---

web/app/business/services/view-model/indicator-value/actual-indicators-value-view-model.service.ts
web/app/business/services/view-model/indicator-value/indicator-value-view-model.service.ts
web/app/ui/components/view/molocule/advanced-multi-line-chart/advanced-multi-line-chart.tsx
web/app/ui/components/view/molocule/multi-line-chart/multi-line-chart.tsx

[EI-185] [web] refactor: Refactor imports in indicator value view models

---

api/package-lock.json
api/package.json

[EI-189] [api] chore: 의존성 추가

---

web/app/business/hooks/indicator/use-indicator-search-list.hooks.ts
web/package-lock.json
web/package.json

[EI-191] [web] fix: use-indicator-search-list

---

web/app/ui/components/view/molocule/expandable-list-item/expandable-list-item.stories.tsx

[EI-195] [web] refactor: Refactor expandable list item component

---

api/src/numerical-guidance/domain/indicator-board-metadata.ts
api/src/numerical-guidance/domain/rule/IndicatorIdInSectionsShouldBeInIndicator.rule.ts
api/src/numerical-guidance/infrastructure/adapter/persistence/custom-forecast-indicator/custom-forecast-indicator.persistent.adapter.ts
api/src/numerical-guidance/infrastructure/adapter/persistence/custom-forecast-indicator/mapper/custom-forecast-indicator.mapper.ts
api/src/numerical-guidance/infrastructure/adapter/persistence/indicator-board-metadata/indicator-board-metadata.persistent.adapter.ts
api/src/numerical-guidance/infrastructure/adapter/persistence/indicator-board-metadata/mapper/indicator-board-metadata.mapper.ts
api/src/numerical-guidance/test/E2E test/indicator-board-metadata/indicator-board-metadata.e2e.spec.ts
api/src/numerical-guidance/test/integration-test/adapter/persistence/indicator-board-metadata.persistent.adapter.spec.ts
api/src/numerical-guidance/test/unit-test/command/indicator-board-metadata/update-sections.command.handler.spec.ts
api/src/numerical-guidance/test/unit-test/domain/indicator-board-metadata.spec.ts

- 축에 대한 e2e test, handler, domain 테스트 및 비지니스 규칙을 추가했습니다.
- mapper 중에 새로운 entity를 만드는 메서드의 의미를 위해 메서드명을 수정했습니다.

[EI-198] 축 test 추가

---

api/src/numerical-guidance/api/live-indicator/live-indicator.controller.ts
api/src/numerical-guidance/test/E2E test/live-indicator/live-indicator.e2e.spec.ts

- 불필요한 api와 test를 제거했습니다.
- twelve 작업이 완료되면 필요없는 작업은 다 지우는 카이젠이 필수인것 같습니다.

[EI-220] fix

---

api/docker-compose-api.yml
data-modeling-api/forecastModule/forecast.py

- arima 최적화 작업 진행했습니다.
- 이슈를 추적하다보니, 예측모델이 들어갈 때 데이터가 전처리 되는것을 확인해서 모델의 최적화 문제다라는 결론을 내렸습니다.
- optimizationArima 함수에서 정상성을 확인한 후 차분하는 방식을 수정했습니다.

[EI-223] [api] fix: arima 성능개선

---

api/src/main.ts
docker-compose-dev.yml
docker-compose.yml
web/app/store/querys/api-path.ts

Ei 999 deploy

---

api/src/main.ts

[EI-999] [api] fix: Refactor CORS origin to include additional URLs

---

api/dockerfile
api/src/main.ts

[EI-999] [api] chore: Refactor Dockerfile to set NODE_ENV to production

---

api/src/main.ts
web/app/ui/components/linguistic-guidance/chat.tsx
web/app/ui/components/numerical-guidance/indicator-board-metadata/metadata-list/metadata-list-item.tsx
web/app/ui/components/numerical-guidance/indicator-board-metadata/metadata-list/metadata-list.tsx
web/app/ui/components/numerical-guidance/indicator-board/indicator-board.tsx
web/app/ui/components/view/atom/draggable/draggable-item.tsx
web/app/ui/components/view/atom/editable-text.tsx
web/app/ui/components/view/atom/message-item.tsx
web/app/ui/components/view/molecule/accordion/accordion-item.tsx
web/app/ui/components/view/molecule/chat-card/chat-card-content.tsx
web/app/ui/components/view/molecule/chat-card/chat-card-header.tsx
web/app/ui/components/view/molecule/chat-card/chat-card-root.tsx
web/app/ui/components/view/molecule/chat-card/chat-card.stories.tsx
web/app/ui/components/view/molecule/expandable-list-item/expandable-list-item-root.tsx
web/app/ui/components/view/molecule/expandable-list-item/expandable-list-item-title.tsx
web/app/ui/components/view/molecule/prompt-form/prompt-form.stories.tsx
web/app/ui/components/view/molecule/prompt-form/prompt-form.tsx
web/app/ui/components/view/molecule/tabs/tabs-list.tsx
web/app/ui/components/view/molecule/tabs/tabs-trigger.tsx
web/app/ui/pages/workspace/side-bar/indicator-list-container.tsx
web/app/ui/pages/workspace/side-bar/sidenav.tsx
web/tailwind.config.ts

Ei 238 style

---

api/src/numerical-guidance/application/command/indicator/insert-indicator-id/insert-indicator-id.command.handler.ts
api/src/numerical-guidance/domain/indicator-board-metadata.ts
api/src/numerical-guidance/test/integration-test/adapter/persistence/indicator-board-metadata.persistent.adapter.spec.ts
api/src/numerical-guidance/test/unit-test/command/custom-forecast-indicator/delete-custom-forecast-indicator-id.command.handler.spec.ts
api/src/numerical-guidance/test/unit-test/command/indicator/delete-indicator-id.command.handler.spec.ts
api/src/numerical-guidance/test/unit-test/domain/indicator-board-metadata.spec.ts

- symbol 추가 
- 변수명 잘못 적용 type -> indicatorType

[EI-235] [api] refactor: indicatorInfo 로직 수정

---

api/src/numerical-guidance/api/indicator/indicator.controller.ts
api/src/numerical-guidance/application/command/indicator/save-indicator-list/dto/save-indicator-list.dto.ts
api/src/numerical-guidance/application/command/indicator/save-indicator-list/save-indicator-list.command.handler.ts
api/src/numerical-guidance/application/command/indicator/save-indicator-list/save-indicator-list.command.ts
api/src/numerical-guidance/application/port/external/twelve/save-indicator-list.port.ts
api/src/numerical-guidance/infrastructure/adapter/persistence/indicator/indicator.persistent.adapter.ts

- 지표 저장 시 country query 값으로 받도록 변경했습니다.
- count가 기준 저장 값인 1000보다 작은 경우 1000개를 그냥 저장하던 오류가 있었습니다. 이를 해결했습니다.

[EI-240] [api] refactor: 지표 저장 시- country query 값으로 받기

---

web/app/ui/components/linguistic-guidance/chat.tsx
web/app/ui/components/numerical-guidance/indicator/indicator-list/indicator-list-item.tsx
web/app/ui/components/numerical-guidance/indicator/indicator-list/indicator-list-result.tsx
web/app/ui/components/numerical-guidance/indicator/indicator-list/indicator-list.tsx
web/app/ui/components/view/atom/message-item.tsx
web/app/ui/components/view/hooks/use-submit.hooks.ts
web/app/ui/components/view/molecule/chat-card/chat-card-content.tsx
web/app/ui/components/view/molecule/chat-card/chat-card-root.tsx
web/app/ui/components/view/molecule/prompt-form/prompt-form.tsx
web/app/ui/components/view/molecule/toggle-group/toggle-group-root.tsx
web/app/ui/pages/workspace/side-bar/indicator-list-container.tsx
web/app/ui/pages/workspace/side-bar/sidenav.tsx
web/app/workspace/error.tsx
web/app/workspace/layout.tsx

Ei 242 layout

---

web/app/business/hooks/indicator-board/use-indicator-board.hook.ts
web/app/business/services/chart/indicator-formatter.service.ts
web/app/business/services/chart/unit-calculator/change-unit-calculator.service.ts
web/app/business/services/chart/unit-calculator/default-unit-calculator.service.ts
web/app/business/services/chart/unit-calculator/index-unit-calculator.service.ts
web/app/business/services/chart/unit-calculator/unit-calculator.service.ts
web/app/business/services/view-model/indicator-value/indicator-value-view-model.service.ts
web/app/ui/components/util/error-boundary.tsx
web/app/ui/components/view/molecule/multi-line-chart/multi-line-chart.tsx
web/app/utils/date-formatter.ts

Ei 242 error

---

data-modeling-api/service.py

[EI-237] [api] fix: granger 검정 버그 수정

---

.gitignore
apps/web/next.config.js
package.json
turbo.json

Ei 999 turbo web

---

turbo.json

[EI-999] [infra] chore: Remove OPENAI_API_KEY from turbo.json

---

apps/web/app/layout.tsx
apps/web/package.json
package-lock.json

Ei 999 logging

---

apps/web/app/layout.tsx
apps/web/app/logging/logging-context.tsx
apps/web/app/logging/provider/google-analytics-provider.tsx
apps/web/app/ui/components/numerical-guidance/indicator-board-metadata/metadata-list-item/metadata-list-item.tsx

- 로깅을 선언적으로 의존성 주입을 통해 결정하도록 수정

Ei 999 logging code

---

package-lock.json

[EI-251] [infra] chore: artillery test 설정

---

apps/web/__tests__/business/hooks/indicator-board-metadata/use-indicator-board-metadata-list-view-model.hook.test.tsx
apps/web/app/business/hooks/numerical-guidance/indicator-board-metedata/use-indicator-board-metadata-list-view-model.hook.ts
apps/web/app/logging/logging-context.ts
apps/web/app/logging/provider/google-analytics-provider.tsx
apps/web/app/store/querys/numerical-guidance/indicator-board-metadata.query.ts
apps/web/app/ui/components/linguistic-guidance/chat.tsx
apps/web/app/ui/components/numerical-guidance/indicator-board-metadata/metadata-dialog-menu/metadata-dialog-menu.tsx
apps/web/app/ui/components/numerical-guidance/indicator-board-metadata/metadata-list-item/metadata-list-item.tsx
apps/web/app/ui/components/numerical-guidance/indicator-board-metadata/metadata-list/metadata-create-button.tsx
apps/web/app/ui/components/numerical-guidance/indicator-board-metadata/metadata-list/metadata-list.tsx
apps/web/app/ui/components/view/hooks/use-toast.ts
apps/web/app/ui/components/view/hooks/usePending.hook.ts
apps/web/app/ui/pages/workspace/side-bar/sidenav.tsx
apps/web/app/ui/pages/workspace/split-screen/split-screen-toggle-group.tsx

Ei 252 logging

---

apps/api/src/numerical-guidance/test/E2E test/indicator/indicator.e2e.spec.ts

[EI-255] [api] test: test 오류 수정

---

.github/workflows/CI-CD.yml
apps/api/docker-compose-api.yml
apps/api/src/utils/config/typeorm.config.service.ts
apps/data-modeling-api/database.py

- 데이터베이스 마이그레이션
- ci/cd 파이프라인 수정

Ei 999 database

---

apps/web/app/logging/component/log-click.tsx
apps/web/app/ui/components/domain/numerical-guidance/indicator-board-metadata/metadata-list/metadata-create-button.tsx
apps/web/app/ui/components/view/molecule/prompt-form/prompt-form.tsx
turbo.json

- 로깅 과정 일부 수정
- chat 두번 쳐지는 버그 수정

Ei 999 logging component

---

apps/web/__tests__/components/numerical-guidance/indicator-board-metadata/metadata-list.test.tsx
apps/web/app/business/hooks/numerical-guidance/custom-forecast-indicator/use-custom-forecast-indicator-list-view-model.hook.ts
apps/web/app/business/hooks/numerical-guidance/indicator-board-metedata/use-indicator-board-metadata-list-view-model.hook.ts
apps/web/app/business/services/numerical-guidance/chart/indicator-formatter.service.ts
apps/web/app/business/services/numerical-guidance/view-model/custom-forecast-indicator-view-model.service.ts
apps/web/app/business/services/numerical-guidance/view-model/indicator-board-metadata/indicator-board-metadata-list-view-model.service.ts
apps/web/app/business/services/numerical-guidance/view-model/indicator-value/custom-forecast-indicator-value-view-model.service.ts
apps/web/app/ui/components/domain/numerical-guidance/indicator-board-metadata/metadata-list-item/metadata-list-item.tsx
apps/web/app/ui/components/view/molecule/expandable-list-item/expandable-list-item-root.tsx
apps/web/app/utils/helper.ts

Ei 254 fix

---

apps/web/app/business/hooks/numerical-guidance/custom-forecast-indicator/use-custom-forecast-indicator-value-by-metadata.hook.ts
apps/web/app/store/querys/numerical-guidance/custom-forecast-indicator.query.ts
apps/web/app/ui/components/domain/numerical-guidance/custom-forecast-indicator/custom-forecast-indicator-edit-dialog-menu/custom-forecast-indicator-edit-dialog-menu.tsx

- 예측지표 부하를 줄이기 위해 cache 로직을 적용하였습니다.
- 데이터를 불러올 때 일괄적으로 불러오는 것이 아닌 cache를 통해 변경된 부분만 불러오도록 했습니다.
- mutate 시 전체를 불러오는게 아닌 변경된 부분만 업데이트 하도록 수정했습니다
다음 작업
- indicator value에도 해당 로직을 적용할 예정입니다
- infra에 값의 경우 캐시를 활용하여 최적화를 진행할 예정입니다

Ei 254 bug fix

---

apps/api/package.json
apps/api/src/numerical-guidance/application/query/custom-forecast-indicator/get-custom-forecast-indicator-values/get-custom-forecast-indicator-values.query.handler.ts
apps/api/src/numerical-guidance/test/unit-test/query/custom-forecast-indicator/get-custom-forecast-indicator-values.query.handler.spec.ts
apps/api/src/utils/type/type-definition.d.ts
apps/web/app/business/services/numerical-guidance/view-model/indicator-value/custom-forecast-indicator-value-view-model.service.ts
apps/web/app/store/querys/numerical-guidance/custom-forecast-indicator.query.ts
apps/web/app/store/querys/numerical-guidance/indicator.query.ts
apps/web/app/store/querys/use-swr-cache.hook.ts
apps/web/tsconfig.json

- 예측지표 쪽 로직 수정(타겟 지표 값이 더 이상 오지 않도록)
- 지표 값 cache를 통해 불러오는 횟수와 시간 대폭 수정

Ei 254 custom indicator fix

---

apps/web/app/page.tsx
apps/web/app/store/querys/numerical-guidance/indicator-board-metadata.query.ts
apps/web/app/ui/components/domain/numerical-guidance/custom-forecast-indicator/custom-forecast-indicator-list/custom-forecast-indicator-list.tsx
apps/web/app/ui/components/domain/numerical-guidance/indicator-board-metadata/metadata-list-item/metadata-list-item-draggable-row.tsx
apps/web/app/ui/components/domain/numerical-guidance/indicator-board-metadata/metadata-list-item/metadata-list-item-row.tsx
apps/web/app/ui/components/domain/numerical-guidance/indicator-board-metadata/metadata-list-item/metadata-list-item.tsx
apps/web/app/ui/components/domain/numerical-guidance/indicator-board-metadata/metadata-list/metadata-list.tsx
apps/web/app/ui/components/domain/numerical-guidance/indicator/indicator-list/indicator-list-result.tsx
apps/web/app/ui/components/domain/numerical-guidance/indicator/indicator-list/indicator-search-bar.tsx
apps/web/app/ui/components/view/atom/icons/icon-button.tsx
apps/web/app/ui/components/view/molecule/side-navigation-bar/side-navigation-bar-root.tsx
apps/web/app/ui/components/view/molecule/side-navigation-bar/side-navigation-bar.stories.tsx
apps/web/app/ui/components/view/molecule/toggle-group/toggle-group-root.tsx
apps/web/app/ui/pages/workspace/side-bar/indicator-board-toolbar.tsx
apps/web/app/ui/pages/workspace/side-bar/indicator-list-container.tsx
apps/web/app/ui/pages/workspace/side-bar/sidenav.tsx

[EI-257] [web] feat: Update side navigation bar ID to "navigation"

---

apps/web/app/(sub-page)/workspace/layout.tsx
apps/web/app/(sub-page)/workspace/page.tsx
apps/web/app/ui/components/domain/linguistic-guidance/chat.tsx
apps/web/app/ui/components/domain/numerical-guidance/indicator-board/indicator-board.tsx
apps/web/app/ui/components/view/atom/message-item.tsx
apps/web/app/ui/components/view/molecule/messages.tsx
apps/web/app/ui/components/view/molecule/side-navigation-bar/side-navigation-bar-root.tsx
apps/web/app/ui/components/view/molecule/toggle-group/toggle-group-root.tsx
apps/web/app/ui/pages/workspace/chat-ai-navigator.tsx
apps/web/app/ui/pages/workspace/split-screen/split-screen-toggle-group.tsx

Ei 257 chat

---

apps/api/src/numerical-guidance/infrastructure/adapter/persistence/custom-forecast-indicator/custom-forecast-indicator.persistent.adapter.ts
apps/api/src/numerical-guidance/infrastructure/adapter/twelve/indicator.twelve.adapter.ts
apps/api/src/numerical-guidance/infrastructure/adapter/twelve/util/twelve-api.manager.ts
apps/api/src/numerical-guidance/numerical-guidance.module.ts
apps/web/app/business/services/auth/sign-in.service.ts

Ei 999 beta fix

---

apps/web/__tests__/components/numerical-guidance/indicator-board-metadata/metadata-list.test.tsx
apps/web/app/business/hooks/numerical-guidance/indicator-board-metedata/use-selected-indicator-board-metadata-view-model.hook.ts
apps/web/app/business/hooks/use-workspace.hook.ts
apps/web/app/business/services/numerical-guidance/chart/indicator-formatter.service.ts
apps/web/app/business/services/numerical-guidance/view-model/indicator-value/indicator-value-view-model.service.ts
apps/web/app/store/stores/numerical-guidance/workspace.store.ts
apps/web/app/ui/components/domain/linguistic-guidance/chat.tsx
apps/web/app/ui/components/domain/numerical-guidance/indicator-board-metadata/metadata-list/metadata-list.tsx
apps/web/app/ui/components/domain/numerical-guidance/indicator-board/indicator-board.tsx
apps/web/app/ui/components/domain/numerical-guidance/indicator/indicator-list/indicator-list-result.tsx
apps/web/app/ui/components/domain/numerical-guidance/indicator/simple-indicators-chart.tsx
apps/web/app/ui/components/view/atom/skeleton.tsx
apps/web/app/ui/components/view/molecule/blank.tsx
apps/web/app/ui/components/view/molecule/tabs/tabs-trigger.tsx
apps/web/app/ui/components/view/skeletons.tsx
apps/web/app/ui/components/view/ui/skeleton.tsx
apps/web/app/ui/pages/workspace/side-bar/custom-forecast-indicator-list-container.tsx
apps/web/app/ui/pages/workspace/side-bar/indicator-board-toolbar.tsx
apps/web/app/ui/pages/workspace/side-bar/metadata-list-container.tsx
apps/web/app/utils/date-formatter.ts

- 스켈레톤 작업
- 메타데이터 클릭여부에 따른 반응형 UI
- 지수 추가했을때 오류 수정

Ei 999 beta hot fix

---

apps/web/app/business/hooks/linguistic-guidance/use-analyze-economy.hook.ts
apps/web/app/business/hooks/linguistic-guidance/use-predict-indicator.hook.ts
apps/web/app/business/hooks/linguistic-guidance/use-recommend-indicator.hook.ts
apps/web/app/logging/component/log-click.tsx
apps/web/app/logging/logging-context.ts
apps/web/app/logging/use-logger.hook.ts
apps/web/app/ui/components/domain/linguistic-guidance/chat.tsx
apps/web/app/ui/components/domain/numerical-guidance/indicator-board-metadata/metadata-dialog-menu/metadata-dialog-menu.tsx
apps/web/app/ui/components/domain/numerical-guidance/indicator-board-metadata/metadata-list-item/metadata-list-item.tsx
apps/web/app/ui/components/view/molecule/side-navigation-bar/side-navigation-bar-root.tsx
apps/web/app/ui/pages/workspace/side-bar/sidenav.tsx
apps/web/app/ui/pages/workspace/split-screen/split-screen-toggle-group.tsx
apps/web/app/utils/hooks/use-toast.ts

- GPT가 생성하는 메타데이터 로깅 하도록 수정
- 뷰모드 체류시간 로깅에 담아 보내도록 수정

Ei 260 logging

---

apps/web/__tests__/business/hooks/indicator/use-indicators-value-view-model.hook.test.tsx
apps/web/__tests__/business/hooks/indicator/use-spark-indicators-value-view-model.hook.test.tsx
apps/web/app/business/hooks/numerical-guidance/custom-forecast-indicator/use-creating-custom-forecast-indicator.hook.ts
apps/web/app/business/hooks/numerical-guidance/indicator/use-spark-indicators-value-view-model.hook.ts
apps/web/app/business/services/numerical-guidance/chart/linear-regression/geometric-series-calculator.service.ts
apps/web/app/business/services/numerical-guidance/view-model/indicator-value/spark-indicator-value-view-model.service.ts
apps/web/app/store/querys/numerical-guidance/indicator-value.query.ts
apps/web/app/ui/components/domain/numerical-guidance/custom-forecast-indicator/custom-forecast-indicator-create-dialog-menu/custom-forecast-indicator-create-dialog-menu.tsx
apps/web/app/ui/components/domain/numerical-guidance/custom-forecast-indicator/custom-forecast-indicator-create-dialog-menu/custom-forecast-indicator-create-spark-chart.tsx
apps/web/app/ui/components/domain/numerical-guidance/custom-forecast-indicator/custom-forecast-indicator-create-dialog-menu/source-indicator-create-slider-group.tsx
apps/web/app/ui/components/domain/numerical-guidance/custom-forecast-indicator/custom-forecast-indicator-create-dialog-menu/steps/select-source-indicator-step-dialog-menu.tsx
apps/web/app/ui/components/domain/numerical-guidance/custom-forecast-indicator/source-indicator-slider.tsx
apps/web/app/ui/components/view/atom/color-cubic.tsx
apps/web/app/ui/components/view/molecule/dialog-menu/dialog-menu-root.tsx
apps/web/app/ui/components/view/molecule/dialog-menu/dialog-menu.style.ts
apps/web/app/ui/components/view/molecule/multi-line-chart/line-chart.tsx
apps/web/app/ui/components/view/molecule/multi-line-chart/multi-line-chart.tsx
apps/web/app/ui/components/view/molecule/spark-chart/spark-area-chart.tsx
apps/web/app/ui/components/view/molecule/spark-chart/spark-chart.stories.tsx
apps/web/app/ui/components/view/molecule/spark-chart/spark-chart.tsx
apps/web/app/utils/date-formatter.ts
apps/web/app/utils/helper.ts
apps/web/app/utils/hooks/use-stepper.hook.tsx
apps/web/app/utils/style/color.ts
apps/web/app/utils/tremor/chart-data-formatter.ts

Ei 16 spark chart

---

apps/api/src/auth/test/E2E test/auth.e2e.spec.ts
apps/api/src/auth/test/unit-test/auth.service.spec.ts
apps/api/src/numerical-guidance/infrastructure/adapter/persistence/indicator-board-metadata/indicator-board-metadata.persistent.adapter.ts
apps/api/src/numerical-guidance/test/integration-test/adapter/fred/indicator.fred.adapter.spec.ts
apps/api/src/numerical-guidance/test/integration-test/adapter/persistence/history-indicator.persistent.adapter.spec.ts
apps/api/src/numerical-guidance/test/integration-test/adapter/persistence/indicator-board-metadata.persistent.adapter.spec.ts
apps/api/src/numerical-guidance/test/integration-test/adapter/persistence/indicator.persistent.adapter.spec.ts
apps/api/src/numerical-guidance/test/integration-test/adapter/storage/file.supabase.adapter.spec.ts
apps/api/src/numerical-guidance/test/integration-test/adapter/twelve/indicator.twelve.adapter.spec.ts
apps/api/src/numerical-guidance/test/unit-test/query/indicator-board-metadata/get-indicator-board-metadata-list.query.handler.spec.ts
apps/api/src/numerical-guidance/test/unit-test/query/indicator-board-metadata/get-indicator-board-metadata.query.handler.spec.ts

- WSL2 에서 테스트가 timeout 문제로 제대로 동작하지 않아 이 시간을 수정함

[EI-264] [api] fix: 테스트 타임아웃 시간 수정

---

apps/web/app/store/querys/api-path.ts

- api url을 동적으로 할당할 수 있게 환경변수로 만들었습니다

[EI-999] [web] refactor: update API_URL to use environment variable

---

apps/api/src/numerical-guidance/test/data/live-economy-indicator-test-data.ts
apps/api/src/numerical-guidance/test/integration-test/adapter/fred/indicator.fred.adapter.spec.ts

- 통합테스트에서 문제가 발생하던 부분에 대한 데이터의 최신화
- 데이터의 비교 테스트보단 유효성 검사를 진행하도록 코드를 수정
- 문제가 발생한 이유는 외부 API로부터 받아온 데이터가 시간이 지남에 따라 변화하기 때문에 발생했음
- 해당 문제를 해결하기 위해 테스트를 진행하기 전에 테스트 데이터를 최신화하는 코드를 추가했음 그러나 같은 엔드포인트에서 받아온 데이터를 서로 비교하는 것을 굳이 테스트할 필요가 없다고 생각했음
- 통합 테스트는 여러 구성 요소나 모듈이 함께 작동하는지를 검증하기 위해 수행되는 테스트이므로 아래 요소들이 좀 더 중요한 것이라 생각했음
1. 데이터 일관성 검증
2. 버그 및 오류 조기 발견
3. 시스템의 신뢰성 향상
4. 변경 사항에 대한 검증
- 때문에 응답데이터에 대한 필드 유효성 검사를 진행하는 것으로 코드를 수정함

Ei 264 hotfix

---

.husky/prepare-commit-msg

- 새로운 지라 이슈번호에 맞게 prepare-commit-msg 수정하였습니다

[KAN-18] [infra] chore: add KAN issue pattern

---

apps/web/app/business/hooks/numerical-guidance/indicator-board-metedata/use-indicator-board-metadata-list-view-model.hook.ts
apps/web/app/business/hooks/numerical-guidance/indicator-board-metedata/use-indicator-board-metadata-view-model.hook.ts
apps/web/app/business/hooks/use-view-mode.hook.ts
apps/web/app/business/services/numerical-guidance/view-model/indicator-board-metadata/indicator-board-metadata-view-model.service.ts
apps/web/app/mocks/db/index.ts
apps/web/app/mocks/db/indicator-board-metadata-action.mock.ts
apps/web/app/store/querys/numerical-guidance/indicator-board-metadata.query.ts
apps/web/app/ui/components/domain/numerical-guidance/indicator-board/indicator-board.tsx
apps/web/app/ui/components/domain/numerical-guidance/indicator-board/view-mode-trigger-button.tsx
apps/web/app/ui/components/domain/numerical-guidance/indicator/base-interval-toggle-group.tsx
apps/web/app/ui/components/domain/numerical-guidance/indicator/simple-indicators-chart.tsx

- 차트에 지표가 없을 때 noDataText가 표시되지 않는 버그 수정
- 2 split 시 화면이 깨지는 현상 수정
- viewMode를 토글 할 수 있도록 개선
- 축 추가 및 삭제 버그 수정
- 메타데이터를 updateAt 기준으로 정렬하도록 수정

Mc 111 refactor
